# openapi: 3.0.0
# info:
#   title: My API
#   version: "1.0"

# servers:
#   - url: "/"

# paths:

#   /points:
#     post:
#       operationId: "endpoints.insert_facts"
#       summary: Upload and insert data from a CSV file
#       parameters:
#         - name: filename
#           in: query
#           description: ""
#           schema: 
#             type: string
#           required: True
#         - name: gender
#           in: query
#           description: ""
#           schema: 
#             type: string
#           required: True
#         - name: invoice_id
#           in: query
#           description: ""
#           schema: 
#             type: string
#           required: True
#         - name: date
#           in: query
#           description: ""
#           schema: 
#             type: string
#             format: date
#           required: True
#         - name: quantity
#           in: query
#           description: ""
#           schema: 
#             type: number
#             format: float
#           required: True
#         - name: total_price
#           in: query
#           description: ""
#           schema: 
#             type: number
#             format: float
#           required: True    
#       responses:
#         '200':
#           description: OK

# openapi: 3.0.0
# info:
#   title: My API
#   version: "1.0"

# servers:
#   - url: "/"

# paths:

#   /points:
#     post:
#       operationId: "endpoints.insert_facts"
#       summary: Upload and insert data from a CSV file
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 file:
#                   type: string
#                   # format: binary
#                 gender:
#                   type: string
#                 invoice_id:
#                   type: string
#                 date:
#                   type: string
#                   format: date
#                 quantity:
#                   type: string
#                   # format: float
#                 total_price:
#                   type: string
#                   # format: float
#       responses:
#         '200':
#           description: OK


  # /points/facts:
  #   post:
  #     operationId: "endpoints.top_10_customer_expected_purchase_in_30_days"
  #     summary: Insert data into the Facts table
  #     parameters:
  #       - name: filename
  #         in: query
  #         description: ""
  #         schema: 
  #           type: string
  #         required: True
  #       - name: customer_id
  #         in: query
  #         description: ""
  #         schema: 
  #           type: string
  #         required: True
        # - name: gender
        #   in: query
        #   description: ""
        #   schema: 
        #     type: string
        #   required: True
        # - name: invoice_id
        #   in: query
        #   description: ""
        #   schema: 
        #     type: string
        #   required: True
        # - name: date
        #   in: query
        #   description: ""
        #   schema: 
        #     type: string
        #     format: date
        #   required: True
        # - name: quantity
        #   in: query
        #   description: ""
        #   schema: 
        #     type: number
        # - name: total_price
        #   in: query
        #   description: ""
        #   schema: 
        #     type: number            
      #     required: True                              
      # responses:
      #   '200':
      #     description: OK



# paths:
#   /points:
#     post:
#       summary: Upload and insert data from a CSV file
#       requestBody:
#         content:
#           text/csv:
#             schema:
#               type: string
#               format: binary
#       responses:
#         '200':
#           description: OK
          
  # /points/facts:
  #   post:
  #     summary: Insert data into the Facts table
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               customer_id:
  #                 type: string
  #               gender:
  #                 type: string
  #               invoice_id:
  #                 type: string
  #               date:
  #                 type: string
  #               quantity:
  #                 type: number
  #               total_price:
  #                 type: number
  #             required:
  #               - customer_id
  #               - gender
  #               - invoice_id
  #               - date
  #               - quantity
  #               - total_price
  #       responses:
  #         '200':
  #           description: OK



# openapi: 3.0.0
# info:
#   title: My API
#   version: "1.0"

# servers:
#   - url: "/"

# paths:

#   /points:
#     post:
#       operationId: "endpoints.insert_facts"
#       summary: Upload and insert data from a CSV file
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               type: object
#               properties:
#                 file:
#                   type: string
#                   # format: binary
#                 gender:
#                   type: string
#                 invoice_id:
#                   type: string
#                 date:
#                   type: string
#                   format: date
#                 quantity:
#                   type: string
#                   # format: float
#                 total_price:
#                   type: string
#                   # format: float
#       responses:
#         '200':
#           description: OK

#   /points/facts:
#     post:
#       operationId: "endpoints.top_10_customer_expected_purchase_in_30_days"
#       summary: Insert data into the Facts table
#       parameters:
#         - name: filename
#           in: query
#           description: ""
#           schema: 
#             type: string
#           required: true
#         - name: customer_id
#           in: query
#           description: ""
#           schema: 
#             type: string
#           required: true
#       responses:
#         '200':
#           description: OK

# openapi: 3.0.0
# info:
#   title: My API
#   version: "1.0"

# servers:
#   - url: "/"

# paths:

  # /points:
  #   post:
  #     operationId: "endpoints.insert_facts"
  #     summary: Upload and insert data from a CSV file
  #     requestBody:
  #       required: true
  #       content:
  #         multipart/form-data:
  #           schema:
  #             type: object
  #             properties:
  #               file:
  #                 type: string
  #                 # format: binary
  #               gender:
  #                 type: string
  #               invoice_id:
  #                 type: string
  #               date:
  #                 type: string
  #                 format: date
  #               quantity:
  #                 type: string
  #                 # format: float
  #               total_price:
  #                 type: string
  #                 # format: float
  #               customer_id:
  #                 type: string
  #             required:
  #               - file
  #               - customer_id
  #               - gender
  #               - invoice_id
  #               - date
  #               - quantity
  #               - total_price
  #     responses:
  #       '200':
  #         description: OK

  # /points/facts:
  #   post:
  #     operationId: "endpoints.top_10_customer_expected_purchase_in_30_days"
  #     summary: Insert data into the Facts table
  #     parameters:
  #       - name: filename
  #         in: query
  #         description: ""
  #         schema: 
  #           type: string
  #         required: true
  #       - name: customer_id
  #         in: query
  #         description: ""
  #         schema: 
  #           type: string
  #         required: true
  #     responses:
  #       '200':
  #         description: OK



openapi: 3.0.0
info:
  title: My API
  version: "1.0"

servers:
  - url: "/"

paths:
  /points:
    post:
      operationId: "endpoints.insert_facts"
      summary: Upload and insert data from a CSV file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  # format: binary
                gender:
                  type: string
                invoice_id:
                  type: string
                date:
                  type: string
                  format: date
                quantity:
                  type: string
                  # format: float
                total_price:
                  type: string
                  # format: float
                customer_id:
                  type: string
              required:
                - file
                - customer_id
                - gender
                - invoice_id
                - date
                - quantity
                - total_price
      responses:
        '200':
          description: OK

  /points/facts:
    post:
      operationId: "endpoints.top_10_customer_expected_purchase_in_30_days"
      summary: Insert data into the Facts table
      parameters:
        - name: filename
          in: query
          description: ""
          schema: 
            type: string
          required: true
        - name: customer_id
          in: query
          description: ""
          schema: 
            type: string
          required: true
      responses:
        '200':
          description: OK
