openapi: 3.0.0
info:
  title: My API
  version: "1.0"

servers:
  - url: "/"

paths:

  /points:
    post:
      operationId: "endpoints.insert_facts"
      summary: Upload and insert data from a CSV file
      parameters:
        - name: filename
          in: query
          description: ""
          schema: 
            type: string
          required: True
      responses:
        '200':
          description: OK

  /points/facts:
    post:
      operationId: "endpoints.top_10_customer_expected_purchase_in_30_days"
      summary: Insert data into the Facts table
      parameters:
        - name: filename
          in: query
          description: ""
          schema: 
            type: string
          required: True
      responses:
        '200':
          description: OK



# paths:
#   /points:
#     post:
#       summary: Upload and insert data from a CSV file
#       requestBody:
#         content:
#           text/csv:
#             schema:
#               type: string
#               format: binary
#       responses:
#         '200':
#           description: OK
          
  # /points/facts:
  #   post:
  #     summary: Insert data into the Facts table
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               customer_id:
  #                 type: string
  #               gender:
  #                 type: string
  #               invoice_id:
  #                 type: string
  #               date:
  #                 type: string
  #               quantity:
  #                 type: number
  #               total_price:
  #                 type: number
  #             required:
  #               - customer_id
  #               - gender
  #               - invoice_id
  #               - date
  #               - quantity
  #               - total_price
  #       responses:
  #         '200':
  #           description: OK
